### ISSUE TITLE
Correção: classes DAO's + Service

### ISSUE THREAD

**Issue by guhpenido** [luqczinn/locacar#61]
### MUDANÇA DE MANIPUALAÇÃO BD

- A forma de manipualação do banco de dados foi alterada, favor **re-construir os DAO's** que foram criados por você e verificar as excessões. 
- Verifique o funcionamento.

Exemplo de manipulação de adicionar:

> public static Veiculo cadastrarVeiculoBD(int ano, String placa, String marca, String tipoMotor, String modeloCarro, double kmRodados, double valorAluguel, String status, String tipo, String cambio) throws SQLException {
> 
>         if (consultarPorPlaca(placa) == null | listarVeiculosBD() == null) {
>             Veiculo v = new Veiculo(ano, placa, marca, tipoMotor, modeloCarro, kmRodados, valorAluguel, status, tipo, cambio);
>             
>             String sql = "INSERT INTO veiculos VALUES("+ano+",'"+placa+"','"+marca+"','"+tipoMotor+"','"+modeloCarro+"',"+kmRodados+",'"+tipo+"','"+cambio+"',"+valorAluguel+",'"+status+"')";
>             
>             Connection com = Conexao.getConnection();
>             PreparedStatement pstmt = com.prepareStatement(sql);
>             pstmt.execute();
>             pstmt.close();
>             com.close();
>             return v;
>         }
>         return null;
>     }
>     

**Data limite: 31/10/2022 às 18h**

**Comment by Tetella06** [comment]
### IMPLEMENTAÇÃO DE LOG's
Favor fazer a **chamada de log** de acordo com as respectivas funções no DAO. @Henriquejogos @guhpenido @luqczinn 

- O parâmetro "acao" deve conter o que está sendo feito: exclusão, adição ou edição.
- O parâmetro "descricao" deve conter o que sofre a ação, se foi veículos, se foi reservas, se foi unidades, clientes e funcionários.
           - Ao passar o parâmetro, deve ser concatenado em uma String o alvo.
                     Ex.: VEICULO@HKA-6262, no qual veículo foi quem sofre uma ação e HKA-6262 é a placa/identificação.
           - Para veículos será utilizado a placa, para reservas o ID, para unidade o num. referência/matrícula e para clientes e funcionários o CPF.
- O campo usuário deve conter quem realizou essa ação.

**Assinatura do método:**

> registrarLogs(String acao, String descricao, String usuario) 

_Cada desenvolvedor deve implementar essa função em todos os DAO's que o mesmo criou._

Realizados:

- [ ] @Tetella06 
- [ ] @Henriquejogos 
- [ ] @guhpenido
- [ ] @luqczinn
